[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Next.js handles routing automatically
# No manual redirects needed for Next.js apps

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps"

# Enable Netlify Blobs
[context.production.environment]
  NETLIFY_BLOBS_CONTEXT = "production"

[context.deploy-preview.environment]
  NETLIFY_BLOBS_CONTEXT = "deploy-preview"

[context.branch-deploy.environment]
  NETLIFY_BLOBS_CONTEXT = "branch-deploy"